eureka:
  instance:
    hostname: localhost
    client:
      service-url:
      default-zone: https://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8090
spring:
  application:
    name: students
  config:
    import:  optional:config server:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: 4275db
  jpa:
    hibernate:
      ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  tracing:
    sampling:
      probability: 1.0
